### PR TITLE
pass request headers to TrustedComputerInterface.addTrustedComputer + small doc fix

### PR DESCRIPTION
**Pull request by Alsciende**
Intended to fix issue https://github.com/scheb/two-factor-bundle/issues/17

### CODE REVIEW

**Comment by scheb** [comment]
I can't just merge that. Changing the signature of `addTrustedComputer` would result in a BC break. Users upgrading to that version would run into a PHP error. So the consequence would be to make it version 2.0.

But what if someone else would need a different dependency for their trusted computer feature? Then add a forth parameter and make it version 3.0? The current system obviously isn't extensible enough, so I'm thinking about how to change the implementation to support any user-defined dependencies.

If you have any ideas how to do that, you're welcome.

**Comment by Alsciende** [comment]
Sorry, I didn't thought about BC.

What about sending an object `\Scheb\TwoFactorBundle\Security\TwoFactor\Trusted\TrustedToken` as parameter? This object would have some properties like `secret` (the current `$token`) and `validUntil` and `userAgent` and `clientIP` or `requestHeaders`. 

The method signature would become

    public function addTrustedComputer(\Scheb\TwoFactorBundle\Security\TwoFactor\Trusted\TrustedToken $token);

Then the class TrustedToken could be extended without causing BC breaks.

**Comment by j0k3r** [comment]
Why don't you just use your own `TrustedCookieManager` ?

You have to redefined the `scheb_two_factor.trusted_cookie_manager.class` parameter.
Create a new class which extends `TrustedCookieManager` and update the `createTrustedCookie` method so that you save your extra data from your `TrustedComputer`.

**Comment by scheb** [comment]
I'll close that PR now. We definitely won't do it this way. I keep the original issue open to keep track of that issue.

**Pull request closed without merging**
