### PR TITLE
Make bundle more extensible

### PR DESCRIPTION
**Pull request by umpirsky**
Makes it easier to customize `AuthenticationContext`.

### CODE REVIEW

**Comment by scheb** [comment]
Would you please rebase your branch on current master and remove the PHPUnit-related changes. Thanks!

**Comment by umpirsky** [comment]
@scheb Done, still needed to fix this warnings...

**Comment by scheb** [comment]
You don't get any warnings, if you use PHPUnit 5.3. That's why the version constraint is set to `"phpunit/phpunit": ">=4.8,<5.4"`

**Comment by umpirsky** [comment]
@scheb Oh, ok, I had bad `composer.lock`, thanks!

**Comment by umpirsky** [comment]
@scheb Done.

**Comment by umpirsky** [comment]
@scheb What do you think?

**Comment by scheb** [comment]
I'll have a look this evening.

**Comment by umpirsky** [comment]
@scheb Perfect, thanks!

**Pull request merged**
