### PR TITLE
Add the Yubikey provider

### PR DESCRIPTION
**Pull request by galphanet**
This is the support of the yubikey (www.yubico.com) merged from a private repo.

Please let me know if I need to fix some code style.

### CODE REVIEW

**Comment by scheb** [comment]
Hello, thanks for the contribution, but I think I have to reject this pull request. My impression is that Yubikey is just not common enough to have it shipped together with the bundle. By integrating it, I will implicitly introduce another package to any project using the two-factor-bundle, regardless if the project will use Yubikey or not it.

I'd like to suggest a far better solution, which gives everyone freedom of choice and doesn't introduce unused dependencies: Why not make it a standalone bundle? You basically just need to wrap your classes with the Symfony bundle structure, and in the composer.json add the two-factor-bundle as a requirement. Then everyone who needs that specific two-factor provider can get it by adding your bundle to their project.

And I'd be happy to link your bundle in the authentication providers sections. Let me know if you need any help stetting up the bundle.

**Comment by darookee** [comment]
There already is [a bundle](https://github.com/darookee/u2f-two-factor-bundle) that supports the U2F Yuibkey.

**Comment by Spomky** [comment]
@darookee your bundle may be suggested. It will be great if you could add it in the `composer.json` file. WDYT?

**Comment by scheb** [comment]
Suggestion added. I guess the PR can be closed then.

**Comment by galphanet** [comment]
Hello,

Thanks for the review. I'll do it in a separate bundle as you advised.

@darookee This is the support for the yubikey OTP feature, not the U2F.

**Comment by scheb** [comment]
@galphanet Let me know when your bundle is finished, so I can put it into the suggestions.

**Pull request closed without merging**
