### PR TITLE
Add lazy Renderer service to speedup page load time

### PR DESCRIPTION
**Pull request by umpirsky**
Fixes https://github.com/scheb/two-factor-bundle/issues/59.

### CODE REVIEW

**Comment by umpirsky** [comment]
@scheb Can you review please?

**Comment by scheb** [comment]
Looks good, thanks!

**Comment by zerkms** [comment]
So what was the "problem"? The `templating` service?

I'm not sure I understand the roots of the problem just looking at this code.

**Comment by zerkms** [comment]
Btw, why it is the doctrine dependency now?

**Comment by umpirsky** [comment]
@scheb Thanks for blazing fast reaction! :+1: 

@zerkms Yes. It's not a dependency, it's dev dependency, we need it for [tests](https://travis-ci.org/scheb/two-factor-bundle/jobs/153023226).

**Comment by zerkms** [comment]
@umpirsky but what about some explanation? Was it `templating`? If so - how your app is structured so that it does not use `templating` service? Since all mine always use even for API (fosrestbundle)

**Comment by umpirsky** [comment]
@zerkms Yes, they use it, I just wanted to remove this bundle services from the slowest list. Plus, this seems like a good decoupling.

**Comment by zerkms** [comment]
> Yes, they use it, I just wanted to remove this bundle services from the slowest list

If the app uses it anyway - this change is harmful: it increases CPU + memory load

@scheb so, the change you accepted made the bundle slower and more memory hungry. "Looks good, thanks!" --- does it really look that good to you? :-S

> Plus, this seems like a good decoupling.

Cannot agree with it.

**Comment by umpirsky** [comment]
@zerkms After this you can override `Renderer` and use other template engine then Twig.

Adding 2 services is minor since typcal Symfony app can have more then thousands of services.

**Comment by zerkms** [comment]
> Adding 2 services is minor since typcal Symfony app can have more then thousands of services.

That, plus few extra lazy wrappers. All of that only for someone's graphs to look better.

> After this you can override Renderer and use other template engine then Twig.

If only it was a problem.

I'm off anyway - I shared my thoughts, but you apparently value your performance metrics over performance. So, whatever.
☮

**Comment by umpirsky** [comment]
@zerkms I appreciate your opinion, but this is open source project and there is many ways people use this software. We are putting efforts to make it as flexible as possible with performance in mind of course. I still think that number of services is not a bottleneck.

**Pull request merged**
