### PR TITLE
Make SessionFlagManager extensible

### PR DESCRIPTION
**Pull request by umpirsky**
I have a case where I need to override this class. This saves me from code duplication. :)

### CODE REVIEW

**Comment by scheb** [comment]
Ok, why not ;)

**Comment by umpirsky** [comment]
@scheb Thanks! No, I think my use case is pretty specific, so no bother. :)

Can you please release `v2.5.2` with this change included?

**Comment by scheb** [comment]
Done

**Comment by umpirsky** [comment]
@scheb Thanks! :+1:

**Pull request merged**
