### PR TITLE
don't require symfony/symfony instead its parts

### PR DESCRIPTION
**Pull request by cordoval**
make it require only what is needed
Example:
https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/composer.json#L30-L47

### CODE REVIEW

**Comment by xabbuh** [comment]
You either need to require the ExpressionLanguage component for tests or rewrite them to not mock the `ContainerBuilder` class.

**Comment by scheb** [comment]
Could you please explain what kind of use-case this serves?

**Comment by cordoval** [comment]
we don't require symfony/symfony, that is all, i also don't want to plug the expression component or rewrite the tests so closing, but if someone wants to do it feel free to savage this PR

**Comment by Spomky** [comment]
I agree with that initiative.
I know that components are just sub-repos created from the symfony/symfony monorepo and that it will not change fundmentaly this bundle, but there is no need to require Symfony full stack when only few of the 40+ components are used.

**Comment by xabbuh** [comment]
This is probably not a big issue for most applications at the moment. But in the future Symfony Flex will lead to applications that don't require `symfony/symfony` but only parts of it and having bundles that are explicit in what they really need will help there.

**Comment by cordoval** [comment]
@Spomky use a fork like my patch-1 and you will be fine, the future is now 👍

**Comment by scheb** [comment]
@cordoval Thanks for the explanation. Haven't read into Symfony Flex yet, but if it's the case that there won't be "the framework" in the future but a more flexible plugin-and-play approach, it totally makes sense to add more explicit requirements.

@cordoval If you felt offended by my question, sorry for that. I just wanted to get some context why this change is a good idea, because I need to understand the intention behind it, before I can give my OK for merging it.

So how should we proceed on that?

**Comment by cordoval** [comment]
no offense, just think that you understood the use case, it is basically symfony is bloating size on vendors
many in the community have recognized this, the form component is huge, accounts for most of the bloat together with intl layer that is forced on you when you require symfony/symfony. There is even a distro called symfony empty, where your require only what you use. It is just really the difference between the typical careless project that sizes 400+ MB, to the one that is under 50MB. I don't have interest in contesting this, so i won't argue about it, just saying it because you wanted me to say it. My interest is in saving $ because of docker/overlay and kubernetes reasons for multitenancy and multiprocessing and disk space on clusters.

That said, I can always use my fork. I honestly have no time to rewrite those tests. If it were for me i just merge this PR, but i am ok either way as i am using my fork.

You decide @scheb any route would be good. I don't have many hopes on symfony flex because i just think is not needed and i am doing most of the practices anyways. It is more about sliming down.

have a great day

**Pull request closed without merging**
