### PR TITLE
Allow the TrustedDevices cookies to be configured by domain 

### PR DESCRIPTION
**Pull request by edhelas**
Allow the TrustedDevices cookies to be configured by domain , or fallback to the default request domain if not set.

### CODE REVIEW

**Comment by scheb** [comment]
Look good. Could you please add a test case in TrustedCookieResponseListenerTest for when the domain is explicitly configured?

**Comment by edhelas** [comment]
Will do :)

**Comment by edhelas** [comment]
I added a small test as requested to the PR as requested :)

**Comment by scheb** [comment]
Recognized that the parameter `scheb_two_factor.trusted_device.cookie_domain` was not set. Added it in 857b2ed631e936d74968faf8ef633fa7d8327a22

**Pull request merged**
