### PR TITLE
Feature/translations

### PR DESCRIPTION
**Pull request by lordjancso**
- Added hu and hr translations
- Refactor translation domains from "messages" to "SchebTwoFactorBundle"

### CODE REVIEW

**Comment by scheb** [comment]
> Refactor translation domains from "messages" to "SchebTwoFactorBundle"

This will be a breaking change. Therefore I cannot just merge into the current version. Would you please split the commits into two PRs:

- Added hu and hr translations => branch "master"
- Refactor translation domains from "messages" to "SchebTwoFactorBundle" => branch "4.x"

Thanks!

**Comment by lordjancso** [comment]
@scheb will you merge this one in the future? what is your plan?

**Comment by scheb** [comment]
Wanted to merge this only when I'm creating the 4.x release, so that I'm not missing an additional translation file that has been added to the master in between.

**Note to myself:** After merging check translation folder for additional files.

**Comment by scheb** [comment]
Merged manually due to conflicts. Thanks for your contribution!

**Pull request closed without merging**
