### PR TITLE
Symfony 3.0

### LINKED ISSUE #15: Make bundle compatible with symfony2.7
After upgrading to v2.7 last weekend this bundle started triggering deprecated errors.

```
PHP Deprecated:  Symfony\Component\DependencyInjection\Definition::setFactoryService(doctrine) is deprecated since version 2.6 and will be removed in 3.0. Use Definition::setFactory() instead. in /home/app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Definition.php on line 208
PHP Stack trace:
PHP   1. {main}() /home/app/app/console:0
PHP   2. Symfony\Component\Console\Application->run() /home/app/app/console:27
PHP   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /home/app/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:126
PHP   4. Symfony\Component\HttpKernel\Kernel->boot() /home/app/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:70
PHP   5. Symfony\Component\HttpKernel\Kernel->initializeContainer() /home/app/app/bootstrap.php.cache:2396
PHP   6. Symfony\Component\DependencyInjection\ContainerBuilder->compile() /home/app/app/bootstrap.php.cache:2618
PHP   7. Symfony\Component\DependencyInjection\Compiler\Compiler->compile() /home/app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:614
PHP   8. Symfony\Component\HttpKernel\DependencyInjection\MergeExtensionConfigurationPass->process() /home/app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php:117
PHP   9. Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationPass->process() /home/app/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/MergeExtensionConfigurationPass.php:39
PHP  10. Scheb\TwoFactorBundle\DependencyInjection\SchebTwoFactorExtension->load() /home/app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/MergeExtensionConfigurationPass.php:55
PHP  11. Symfony\Component\DependencyInjection\Loader\XmlFileLoader->load() /home/app/vendor/scheb/two-factor-bundle/DependencyInjection/SchebTwoFactorExtension.php:48
PHP  12. Symfony\Component\DependencyInjection\Loader\XmlFileLoader->parseDefinitions() /home/app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php:58
PHP  13. Symfony\Component\DependencyInjection\Loader\XmlFileLoader->parseDefinition() /home/app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php:119
PHP  14. Symfony\Component\DependencyInjection\Definition->setFactoryService() /home/app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php:153
PHP  15. trigger_error() /home/app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Definition.php:208
```

I have pinpointed the issue, it comes from [Resources/config/persistence.xml](https://github.com/scheb/two-factor-bundle/blob/master/Resources/config/persistence.xml#L7-L9).

I've also provided a solution that fixes this deprication warnings.

```xml
<service id="scheb_two_factor.entity_manager" class="Doctrine\ORM\EntityManager" public="false">
    <factory service="doctrine" method="getManager"/>
    <argument>%scheb_two_factor.model_manager_name%</argument>
</service>
```

Cheers!

### PR DESCRIPTION
**Pull request by j0k3r**
> I started this PR from the sf2.7 branch, that's why there is one commit from @scheb inside.

Should fix #15.

Few remarks:

### CS
I run php-cs-fixer to _clean_ the code and added an `.editorconfig` file too to avoid much noise about coding standard in the future.

### Symfony 3.0
The main work was done on the factory part by @scheb and I just fixed the SecurityContext which, in that case, was easily replaced by the TokenStorage.

### Symfony < 2.6 dropped
Because Symfony 2.6 introduced TokenStorage which isn't supported by previous version.

Also, remove support for `SecureRandom` and use `random_bytes` instead which came with Symfony 2.8. For lower version of Symfony we require `paragonie/random_compat`.

### Circular reference (see https://github.com/scheb/two-factor-bundle/issues/33)
Using the 1.5.0 version I ran into a `ServiceCircularReferenceException` when using the bundle with an other one (which require `templating` engine). You can see the [travis build](https://travis-ci.org/wallabag/wallabag/jobs/98303811).
> Symfony\Component\DependencyInjection\Exception\ServiceCircularReferenceException: Circular reference detected for service "templating", path: "nelmio_api_doc.event_listener.request -> nelmio_api_doc.formatter.html_formatter -> templating -> twig -> security.authorization_checker -> security.access.decision_manager -> scheb_two_factor.security_voter -> scheb_two_factor.provider_collection -> scheb_two_factor.security.email.provider".

It seems that when using templating service we can ran into a `ServiceCircularReferenceException` because it "_relies on a lot of other services, so it is rather easy to have this circular dependency problem_".

The "best", and easiest, solution (which isn't a best practice btw) it to inject the container and then get the templating service.

See: symfony/symfony#2347

But if we don't inject it in the constructor but use assignment instead, we don't have the problem.

### Coveralls
I remove the `src_dir` from `.coveralls.yml` because it seems to be deprecated now.

### Travis
I've added `sudo: false` in travis config file to speed up the build (since using that kind of option, build run on container). Also, I've updated the cache directories so it cache the composer directory (I guess the previous option doesn't work).

Regarding all of that, I think it'll be a good idea to bump 2.0.0 :smile:

### CODE REVIEW

**Comment by ismailbaskin** [comment]
+1

**Comment by scheb** [comment]
Thanks for your fantastic work! I did some changes on that circular reference problem in between, so I was not able to merge it directly in. Instead I cherry-picked your commits over and did the necessary changes. Bundle is now released as version 2.0.

Happy new year everyone! :)

**Comment by j0k3r** [comment]
@scheb excellent !
Happy New Year :tada:

**Comment by FabianPiconeDev** [comment]
Concerning to the "Circular reference" problem.

I **don't** want to inject the container. So i solved this temporary, by using the setter injection, for being able to navigate through the browser.

BUT: I said temporary because, on testing with **PHPUnit**, i still recieve the circular error. I noticed that the error happens in the cache. So after clearing the cache, only the very first test passed. After building the cache, the circular error happens.
So i started to let clear the cache on tearDown() but this massively slows down my tests.

I hope this circular problems will be solved soon?

**Comment by j0k3r** [comment]
[This](https://github.com/scheb/two-factor-bundle/commit/b8887b0f426d1d343c5e403410c163e2bbbf5486) should have fixed the circular reference problem. Are you using the latest version?

**Pull request closed without merging**
