### PR TITLE
Added TwoFactorTokenInterface and TwoFactorTokenFactory

### PR DESCRIPTION
**Pull request by mickpik**

### CODE REVIEW

**Comment by scheb** [comment]
Why? That's the whole point of the TwoFactorToken, to hide away the privileges that should only be granted when two-factor authentication was completed successfully.

**Comment by mickpik** [comment]
Before the two-factor authenticator was completed successfully i do want certain roles on the token. I have a use case where i do not want the two-factor authenticator to kick in directly after login but only when visiting a specific url.

In the v2.* version this could be achieved by using the exclude_pattern. Now i am using the firewall access_control instead.

**Comment by mickpik** [comment]
I agree 2 is a cleaner solution. I will try to make time to implement this

**Comment by scheb** [comment]
Looks good to me. Only thing I don't understand is why you moved all those methods around. Probably your IDE trying to get public/private methods into a certain order. But I'd actually like to keep it as-is, keep the private ones next to the public ones using them.

**Comment by mickpik** [comment]
I agree the preview looks a little weird but if you look closely you will see all i did was add the `getActiveTwoFactorProviders` and `getAuthCodeFromRequest` private methods  to improve testability.

They are above the methods using them: `beginTwoFactorAuthentication` and `attemptAuthentication`.

**Comment by scheb** [comment]
Ah, now I see what you did.

But I don't agree with your way of running tests against private methods using reflection. E.g.:
```php
$method = new \ReflectionMethod(TwoFactorListener::class, 'getAuthCodeFromRequest');
$method->setAccessible(true);
$this->assertEquals('authCode', $method->invokeArgs($this->listener, [$this->request])); 
```

For the unit test, the private method is non-existent. It's a implementation secret of the class, so from the perspective of the test, you cannot even know that this method exists. The class has to have the ability to refactor, rename or remove a private method as it likes, without breaking the tests. Effectively this means, tests should only be executed against the public interface of a class.

If you really want to test the logic in a private method, a valid solution would be to extract it into a separate class to expose the logic publicly and use that new class as a dependency, that can be mocked away.

**Comment by mickpik** [comment]
Thanks for explaining, makes a lot of sense.

But what would be the difference between make these methods private in the original class or moving these methods to a separate class and  exposing them there? It feels unnatural to introduce new classes just for these two methods

**Comment by scheb** [comment]
Jep, you're right, in that case extracting that bit of logic into a separate class doesn't really seem worth it. I just meant that this would be the usual solution, if it seems to be necessary testing a private method.

In our case, I'd say we're better off by testing that behaviour through the public interface. After reviewing it once again, that's exactly what it did before. I have mocked objects, which are providing the values, and I'm checking the values on the result (which is the token). And that resulting value couldn't be there, if the call wasn't made correctly. So everything was in fact tested, no need to test the private methods.

Now, to get this PR wrapped up, would you please revert the additional changes in TwoFactorProviderHandlerTest (except the ones necessary for the TwoFactorTokenFactory)? We can keep the two new private methods for better readability. Besides that, it's looking fine to me.

**Comment by mickpik** [comment]
Yes but since the creation of the token has been moved to the TwoFactorTokenFactory and this class is mocked in the TwoFactorListenerTest and TwoFactorProviderHandlerTest it doesnt return an actual TwoFactorToken but a mocked one.

To overcome this i introduced the two new private methods which cover the functionality which would otherwise be tested through properties on of the returned TwoFactorToken.

So the only way i see to keep the tests as they where before is to provide an actual instance of TwoFactorTokenFactory instead of a mocked one in TwoFactorProviderHandlerTest and TwoFactorListenerTest. This is what i was trying to prevent before since ideally you would want to have one test cover one class. But since the TwoFactorTokenFactory is this simple it might be a solution, what do you think?

**Comment by scheb** [comment]
Thanks for your patience, will take care of the rest.

**Pull request merged**
